module RecordFormats
  module Dif10ControlledElements

    CONTROLLED_ELEMENT_MAP = {
      'Dataset_Citation/Persistent_Identifier/Type'                    => 'DIF/UMM PersistentIdentifierEnum = ["DOI", "ARK"]',
      'Personnel/Role'                                                 => 'DIF/UMM PersonnelRoleEnum = ["INVESTIGATOR", "INVESTIGATOR, TECHNICAL CONTACT", "METADATA AUTHOR", "METADATA AUTHOR, TECHNICAL CONTACT", "TECHNICAL CONTACT"]',
      'Personnel/Contact_Person/Phone/Type'                            => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Personnel/Contact_Group/Phone/Type'                             => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Science_Keywords/Category'                                      => 'GCMD Keywords https://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.csv',
      'Science_Keywords/Topic'                                         => 'GCMD Keywords https://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.csv',
      'Science_Keywords/Term'                                          => 'GCMD Keywords https://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.csv',
      'Science_Keywords/Variable_Level_1'                              => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.csv',
      'Science_Keywords/Variable_Level_2'                              => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.csv',
      'Science_Keywords/Variable_Level_3'                              => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/sciencekeywords/sciencekeywords.csv',
      'Platform/Type'                                                  => 'GCMD Keywords https://gcmdservices.gsfc.nasa.gov/static/kms/platforms/platforms.csv',
      'Platform/Short_Name'                                            => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/platforms/platforms.csv',
      'Platform/Long_Name'                                             => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/platforms/platforms.csv',
      'Platform/Instrument/Short_Name'                                 => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/instruments/instruments.csv',
      'Platform/Instrument/Long_Name'                                  => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/instruments/instruments.csv',
      'Platform/Instrument/Sensor/Short_Name'                          => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/instruments/instruments.csv',
      'Platform/Instrument/Sensor/Long_Name'                           => 'GCMD Keywords https://gcmdservices.gsfc.nasa.gov/static/kms/instruments/instruments.csv',
      'Temporal_Coverage/Range_DateTime/Beginning_Date_Time'           => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Range_DateTime/Ending_Date_Time'              => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Single_Date_Time'                             => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Periodic_DateTime/Start_Date'                 => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Periodic_DateTime/End_Date'                   => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Periodic_DateTime/Duration_Unit'              => 'DIF/UMM DurationUnitEnum = ["DAY", "MONTH", "YEAR"]',
      'Temporal_Coverage/Periodic_DateTime/Period_Cycle_Duration_Unit' => 'DIF/UMM DurationUnitEnum = ["DAY", "MONTH", "YEAR"]',
      'Dataset_Progress'                                               => '',
      'Spatial_Coverage/Spatial_Coverage_Type'                         => 'DIF/UMM SpatialCoverageTypeEnum = ["Horizontal", "HorizontalVertical", "Orbit", "Vertical", "Horizon&amp;Vert"]',
      'Spatial_Coverage/Granule_Spatial_Representation'                => 'DIF/UMM GranuleSpatialRepresentationEnum = ["CARTESIAN", "GEODETIC", "ORBIT", "NO_SPATIAL"]',
      'Spatial_Coverage/Geometry/Coordinate_System'                    => 'DIF/UMM CoordinateSystemEnum = ["CARTESIAN", "GEODETIC"]',
      'Location/Location_Category'                                     => 'GCMD Keywords https://gcmdservices.gsfc.nasa.gov/static/kms/locations/locations.csv',
      'Location/Location_Type'                                         => 'GCMD Keywords https://gcmdservices.gsfc.nasa.gov/static/kms/locations/locations.csv',
      'Location/Location_Subregion1'                                   => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/locations/locations.csv',
      'Location/Location_Subregion2'                                   => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/locations/locations.csv',
      'Location/Location_Subregion3'                                   => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/locations/locations.csv',
      'Data_Resolution/Horizontal_Resolution_Range'                    => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/horizontalresolutionrange/horizontalresolutionrange.csv',
      'Data_Resolution/Vertical_Resolution_Range'                      => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/verticalresolutionrange/verticalresolutionrange.csv',
      'Data_Resolution/Temporal_Resolution_Range'                      => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/temporalresolutionrange/temporalresolutionrange.csv',
      'Project/Short_Name'                                             => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/projects/projects.csv',
      'Project/Long_Name'                                              => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/projects/projects.csv',
      'Dataset_Language'                                               => 'DIF/UMM DatasetLanguageEnum = ["English", "Afrikaans", "Arabic", "Bosnian", "Bulgarian", "Chinese", "Croatian", "Czech", "Danish", "Dutch", "Estonian", "Finnish", "French", "German", "Hebrew", "Hungarian", "Indonesian", "Italian", "Japanese", "Korean", "Latvian", "Lithuanian", "Norwegian", "Polish", "Portuguese", "Romanian", "Russian", "Slovak", "Spanish", "Ukrainian", "Vietnamese"]',
      'Organization/Organization_Type'                                 => 'DIF/UMM OrganizationTypeEnum = ["DISTRIBUTOR", "ARCHIVER", "ORIGINATOR", "PROCESSOR"]',
      'Organization/Organization_Name/Short_Name'                      => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/providers/providers.csv',
      'Organization/Organization_Name/Long_Name'                       => 'GCMD keywords https://gcmdservices.gsfc.nasa.gov/static/kms/providers/providers.csv',
      'Organization/Personnel/Role'                                    => 'DIF/UMM OrganizationPersonnelRoleEnum = ["DATA CENTER CONTACT"]',
      'Organization/Personnel/Contact_Person/Phone/Type'               => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Organization/Personnel/Contact_Group/Phone/Type'                => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Reference/Persistent_Identifier/Type'                           => 'DIF/UMM PersistentIdentifierEnum = ["DOI", "ARK"]',
      'Related_URL/URL_Content_Type/Type'                              => 'UMM-Common JSON schema RelatedUrlTypeEnum = ["GET DATA", "GET SERVICE", "GET RELATED VISUALIZATION", "DATA SET LANDING PAGE", "DOI", "EXTENDED METADATA", "PROFESSIONAL HOME PAGE", "PROJECT HOME PAGE", "VIEW RELATED INFORMATION", "HOME PAGE"]',
      'Related_URL/URL_Content_Type/Subtype'                           => 'UMM-Common JSON schema RelatedURLSubTypeEnum https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/collection/v1.10/umm-cmn-json-schema.json#1527',
      'Related_URL/Protocol'                                           => 'UMM-Common JSON schema GetServiceType Protocol enum = ["HTTP", "HTTPS", "FTP", "FTPS", "Not provided"]',
      'Related_URL/Mime_Type'                                          => 'UMM-Common JSON schema URLMimeTypeEnum https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/collection/v1.10/umm-cmn-json-schema.json#1542',
      'Metadata_Association/Type'                                      => 'DIF/UMM MetadataAssociationTypeEnum = ["Parent", "Child", "Related", "Dependent", "Input", "Science Associated"]',
      'Product_Level_Id'                                               => 'DIF/UMM ProductLevelIdEnum = ["Not provided", "0", "1", "1A", "1B", "1T", "2", "2G", "2P", "3", "4", "NA"], but whenever possible, only NASA approved processing levels ["0", "1", "1A", "1B", "2", "3", "4"] should be used.',
      'Product_Flag'                                                   => 'DIF/UMM ProductFlagEnum = ["Not provided", "DATA_PRODUCT_FILE", "INSTRUMENT_ANCILLARY_FILE", "SYSTEM/SPACECRAFT_FILE", "EXTERNAL_DATA"]',
      'Collection_Data_Type'                                           => 'DIF/UMM CollectionDataTypeEnum = ["SCIENCE_QUALITY", "NEAR_REAL_TIME", "ON_DEMAND", "OTHER"]',
      'Metadata_Version'                                               => 'DIF/UMM MetadataVersionEnum = ["VERSION 9.8.1", "VERSION 9.8.2", "VERSION 9.8.2.2", "VERSION 9.8.3", "VERSION 9.8.4", "VERSION 9.9.3", "VERSION 10.2"]',
      'Metadata_Dates/Metadata_Creation'                               => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Metadata_Last_Revision'                          => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Metadata_Future_Review'                          => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Metadata_Delete'                                 => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Creation'                                   => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Last_Revision'                              => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Future_Review'                              => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Delete'                                     => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Private'                                                        => 'DIF/UMM PrivateEnum = ["True", "False"]'
    }
  end
end
