module RecordFormats
  module Dif10Fields
     SECTION_TITLES = [
      "Summary",
      "Platform",
      "Science_Keywords",
      "Platform",
      "Dataset_Citation",
      "Organization",
      "Personnel",
      "Reference",
      "Location",
      "Data_Resolution",
      "Related_URL",
      "Distribution",
      "Multimedia_Sample",
      "Additional_Attributes",
      "Temporal_Coverage",
      "Spatial_Coverage",
      "Project",
      "Metadata_Dates",
      "Metadata_Association",
      "IDN_Node",
      "Extended_Metadata"
    ]

    REQUIRED_COLLECTION_FIELDS = [
      "Entry_ID/Short_Name",
      "Entry_ID/Version",
      "Entry_Title",
      "Science_Keywords/Category",
      "Science_Keywords/Topic",
      "Science_Keywords/Term",
      "Platform/Short_Name",
      "Platform/Instrument/Short_Name",
      "Temporal_Coverage/Range_DateTime/Beginning_Date_Time",
      "Temporal_Coverage/Range_DateTime/Ending_Date_Time",
      "Temporal_Coverage/Single_Date_Time",
      "Temporal_Coverage/Periodic_DateTime/Name",
      "Temporal_Coverage/Periodic_DateTime/Start_Date",
      "Temporal_Coverage/Periodic_DateTime/End_Date",
      "Temporal_Coverage/Periodic_DateTime/Duration_Unit",
      "Temporal_Coverage/Periodic_DateTime/Duration_Value",
      "Temporal_Coverage/Periodic_DateTime/Period_Cycle_Duration_Unit",
      "Temporal_Coverage/Periodic_DateTime/Period_Cycle_Duration_Value",
      "Temporal_Coverage/Paleo_DateTime/Paleo_Start_Date",
      "Temporal_Coverage/Paleo_DateTime/Paleo_Stop_Date",
      "Dataset_Progress",
      "Spatial_Coverage/Granule_Spatial_Representation",
      "Spatial_Coverage/Geometry/Coordinate_System",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Southernmost_Latitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Northernmost_Latitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Westernmost_Longitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Easternmost_Longitude",
      "Spatial_Coverage/Geometry/Point/Point_Longitude",
      "Spatial_Coverage/Geometry/Point/Point_Latitude",
      "Spatial_Coverage/Geometry/Line/Point/Point_Longitude",
      "Spatial_Coverage/Geometry/Line/Point/Point_Latitude",
      "Spatial_Coverage/Geometry/Polygon/Boundary/Point/Point_Longitude",
      "Spatial_Coverage/Geometry/Polygon/Boundary/Point/Point_Latitude",
      "Organization/Organization_Type",
      "Organization/Organization_Name/Short_Name",
      "Summary/Abstract",
      "Related_URL/URL_Content_Type/Type",
      "Related_URL/URL",
      "Product_Level_Id",
      "Metadata_Dates/Metadata_Creation",
      "Metadata_Dates/Metadata_Last_Revision",
      "Metadata_Dates/Data_Creation",
      "Metadata_Dates/Data_Last_Revision",
      "Dataset_Citation/Persistent_Identifier/Type",
      "Dataset_Citation/Persistent_Identifier/Identifier"
    ]

    DESIRED_FIELDS = [
      "Entry_ID/Short_Name",
      "Entry_ID/Version",
      "Entry_Title",
      "Dataset_Citation/Persistent_Identifier/Type",
      "Dataset_Citation/Persistent_Identifier/Identifier",
      "Personnel/Contact_Group/Name",
      "Science_Keywords/Category",
      "Science_Keywords/Topic",
      "Science_Keywords/Term",
      "Science_Keywords/Variable_Level_1",
      "Science_Keywords/Variable_Level_2",
      "Science_Keywords/Variable_Level_3",
      "Science_Keywords/Detailed_Variable",
      "Platform/Type",
      "Platform/Short_Name",
      "Platform/Long_Name",
      "Platform/Instrument/Short_Name",
      "Platform/Instrument/Long_Name",
      "Platform/Instrument/Sensor/Short_Name",
      "Platform/Instrument/Sensor/Long_Name",
      "Temporal_Coverage/Ends_At_Present_Flag",
      "Temporal_Coverage/Range_DateTime/Beginning_Date_Time",
      "Temporal_Coverage/Range_DateTime/Ending_Date_Time",
      "Temporal_Coverage/Single_Date_Time",
      "Dataset_Progress",
      "Spatial_Coverage/Granule_Spatial_Representation",
      "Spatial_Coverage/Geometry/Coordinate_System",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Center_Point/Point/Point_Longitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Center_Point/Point/Point_Latitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Southernmost_Latitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Northernmost_Latitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Westernmost_Longitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Easternmost_Longitude",
      "Spatial_Coverage/Geometry/Bounding_Rectangle/Minimum_Altitude",
      "Spatial_Coverage/Spatial_Info/Spatial_Coverage_Type",
      "Spatial_Coverage/Spatial_Info/Horizontal_Coordinate_System/Geodetic_Model/Horizontal_DatumName",
      "Spatial_Coverage/Spatial_Info/Horizontal_Coordinate_System/Geodetic_Model/Ellipsoid_Name",
      "Spatial_Coverage/Spatial_Info/Horizontal_Coordinate_System/Geodetic_Model/Semi_Major_Axis",
      "Spatial_Coverage/Spatial_Info/Horizontal_Coordinate_System/Geodetic_Model/Denominator_Of_Flattening_Ratio",
      "Spatial_Coverage/Spatial_Info/Horizontal_Coordinate_System/Geographic_Coordinate_System/GeographicCoordinateUnits",
      "Spatial_Coverage/Spatial_Info/Horizontal_Coordinate_System/Geographic_Coordinate_System/LatitudeResolution",
      "Spatial_Coverage/Spatial_Info/Horizontal_Coordinate_System/Geographic_Coordinate_System/LongitudeResolution",
      "Location/Location_Category",
      "Data_Resolution/Latitude_Resolution",
      "Data_Resolution/Longitude_Resolution",
      "Data_Resolution/Horizontal_Resolution_Range",
      "Data_Resolution/Vertical_Resolution",
      "Data_Resolution/Vertical_Resolution_Unit",
      "Data_Resolution/Vertical_Resolution_Range",
      "Data_Resolution/Temporal_Resolution",
      "Data_Resolution/Temporal_Resolution_Range",
      "Project/Short_Name",
      "Project/Long_Name",
      "Organization/Organization_Type",
      "Organization/Organization_Name/Short_Name",
      "Organization/Organization_Name/Long_Name",
      "Organization/Organization_URL",
      "Organization/Personnel/Contact_Group/Name",
      "Distribution/Distribution_Format",
      "Multimedia_Sample/URL",
      "Multimedia_Sample/Description",
      "Reference/Citation",
      "Summary/Abstract",
      "Related_URL/URL_Content_Type/Type",
      "Related_URL/URL_Content_Type/Subtype",
      "Related_URL/URL",
      "Related_URL/Description",
      "Related_URL/Mime_Type",
      "Product_Level_Id",
      "Collection_Data_Type",
      "Metadata_Dates/Metadata_Creation",
      "Metadata_Dates/Metadata_Last_Revision",
      "Metadata_Dates/Data_Creation",
      "Metadata_Dates/Data_Last_Revision"
    ]

    CONTROLLED_ELEMENT_MAP = {
      'Dataset_Citation/Persistent_Identifier/Type'                    => 'DIF/UMM PersistentIdentifierEnum = ["DOI", "ARK"]',
      'Personnel/Role'                                                 => 'DIF/UMM PersonnelRoleEnum = ["INVESTIGATOR", "INVESTIGATOR, TECHNICAL CONTACT", "METADATA AUTHOR", "METADATA AUTHOR, TECHNICAL CONTACT", "TECHNICAL CONTACT"]',
      'Personnel/Contact_Person/Phone/Type'                            => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Personnel/Contact_Group/Phone/Type'                             => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Science_Keywords/Category'                                      => 'GCMD Keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords?format=csv',
      'Science_Keywords/Topic'                                         => 'GCMD Keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords?format=csv',
      'Science_Keywords/Term'                                          => 'GCMD Keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords?format=csv',
      'Science_Keywords/Variable_Level_1'                              => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords?format=csv',
      'Science_Keywords/Variable_Level_2'                              => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords?format=csv',
      'Science_Keywords/Variable_Level_3'                              => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords?format=csv',
      'Platform/Type'                                                  => 'GCMD Keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/platforms?format=csv',
      'Platform/Short_Name'                                            => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/platforms?format=csv',
      'Platform/Long_Name'                                             => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/platforms?format=csv',
      'Platform/Instrument/Short_Name'                                 => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/instruments?format=csv',
      'Platform/Instrument/Long_Name'                                  => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/instruments?format=csv',
      'Platform/Instrument/Sensor/Short_Name'                          => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/instruments?format=csv',
      'Platform/Instrument/Sensor/Long_Name'                           => 'GCMD Keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/instruments?format=csv',
      'Temporal_Coverage/Range_DateTime/Beginning_Date_Time'           => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Range_DateTime/Ending_Date_Time'              => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Single_Date_Time'                             => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Periodic_DateTime/Start_Date'                 => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Periodic_DateTime/End_Date'                   => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Temporal_Coverage/Periodic_DateTime/Duration_Unit'              => 'DIF/UMM DurationUnitEnum = ["DAY", "MONTH", "YEAR"]',
      'Temporal_Coverage/Periodic_DateTime/Period_Cycle_Duration_Unit' => 'DIF/UMM DurationUnitEnum = ["DAY", "MONTH", "YEAR"]',
      'Dataset_Progress'                                               => 'DIF/UMM DatasetProgressEnum = ["PLANNED", "IN WORK", "COMPLETE"]',
      'Spatial_Coverage/Spatial_Coverage_Type'                         => 'DIF/UMM SpatialCoverageTypeEnum = ["Horizontal", "HorizontalVertical", "Orbit", "Vertical", "Horizon&amp;Vert"]',
      'Spatial_Coverage/Granule_Spatial_Representation'                => 'DIF/UMM GranuleSpatialRepresentationEnum = ["CARTESIAN", "GEODETIC", "ORBIT", "NO_SPATIAL"]',
      'Spatial_Coverage/Geometry/Coordinate_System'                    => 'DIF/UMM CoordinateSystemEnum = ["CARTESIAN", "GEODETIC"]',
      'Location/Location_Category'                                     => 'GCMD Keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/locations?format=csv',
      'Location/Location_Type'                                         => 'GCMD Keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/locations?format=csv',
      'Location/Location_Subregion1'                                   => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/locations?format=csv',
      'Location/Location_Subregion2'                                   => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/locations?format=csv',
      'Location/Location_Subregion3'                                   => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/locations?format=csv',
      'Data_Resolution/Horizontal_Resolution_Range'                    => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/horizontalresolutionrange?format=csv',
      'Data_Resolution/Vertical_Resolution_Range'                      => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/verticalresolutionrange?format=csv',
      'Data_Resolution/Temporal_Resolution_Range'                      => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/temporalresolutionrange?format=csv',
      'Project/Short_Name'                                             => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/projects?format=csv',
      'Project/Long_Name'                                              => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/projects?format=csv',
      'Dataset_Language'                                               => 'DIF/UMM DatasetLanguageEnum = ["English", "Afrikaans", "Arabic", "Bosnian", "Bulgarian", "Chinese", "Croatian", "Czech", "Danish", "Dutch", "Estonian", "Finnish", "French", "German", "Hebrew", "Hungarian", "Indonesian", "Italian", "Japanese", "Korean", "Latvian", "Lithuanian", "Norwegian", "Polish", "Portuguese", "Romanian", "Russian", "Slovak", "Spanish", "Ukrainian", "Vietnamese"]',
      'Organization/Organization_Type'                                 => 'DIF/UMM OrganizationTypeEnum = ["DISTRIBUTOR", "ARCHIVER", "ORIGINATOR", "PROCESSOR"]',
      'Organization/Organization_Name/Short_Name'                      => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/providers?format=csv',
      'Organization/Organization_Name/Long_Name'                       => 'GCMD keywords https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/providers?format=csv',
      'Organization/Personnel/Role'                                    => 'DIF/UMM OrganizationPersonnelRoleEnum = ["DATA CENTER CONTACT"]',
      'Organization/Personnel/Contact_Person/Phone/Type'               => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Organization/Personnel/Contact_Group/Phone/Type'                => 'DIF/UMM PhoneTypeEnum = ["Direct Line", "Primary", "Telephone", "Fax", "Mobile", "Modem", "TDD/TTY Phone", "U.S. toll free", "Other"]',
      'Reference/Persistent_Identifier/Type'                           => 'DIF/UMM PersistentIdentifierEnum = ["DOI", "ARK"]',
      'Related_URL/URL_Content_Type/Type'                              => 'UMM-Common JSON schema RelatedUrlTypeEnum = ["GET DATA", "GET SERVICE", "GET RELATED VISUALIZATION", "DATA SET LANDING PAGE", "DOI", "EXTENDED METADATA", "PROFESSIONAL HOME PAGE", "PROJECT HOME PAGE", "VIEW RELATED INFORMATION", "HOME PAGE"]',
      'Related_URL/URL_Content_Type/Subtype'                           => 'UMM-Common JSON schema RelatedURLSubTypeEnum https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/collection/v1.10/umm-cmn-json-schema.json#1527',
      'Related_URL/Protocol'                                           => 'UMM-Common JSON schema GetServiceType Protocol enum = ["HTTP", "HTTPS", "FTP", "FTPS", "Not provided"]',
      'Related_URL/Mime_Type'                                          => 'UMM-Common JSON schema URLMimeTypeEnum https://git.earthdata.nasa.gov/projects/EMFD/repos/unified-metadata-model/browse/collection/v1.10/umm-cmn-json-schema.json#1542',
      'Metadata_Association/Type'                                      => 'DIF/UMM MetadataAssociationTypeEnum = ["Parent", "Child", "Related", "Dependent", "Input", "Science Associated"]',
      'Product_Level_Id'                                               => 'DIF/UMM ProductLevelIdEnum = ["Not provided", "0", "1", "1A", "1B", "1T", "2", "2G", "2P", "3", "4", "NA"], but whenever possible, only NASA approved processing levels ["0", "1", "1A", "1B", "2", "3", "4"] should be used.',
      'Product_Flag'                                                   => 'DIF/UMM ProductFlagEnum = ["Not provided", "DATA_PRODUCT_FILE", "INSTRUMENT_ANCILLARY_FILE", "SYSTEM/SPACECRAFT_FILE", "EXTERNAL_DATA"]',
      'Collection_Data_Type'                                           => 'DIF/UMM CollectionDataTypeEnum = ["SCIENCE_QUALITY", "NEAR_REAL_TIME", "ON_DEMAND", "OTHER"]',
      'Metadata_Version'                                               => 'DIF/UMM MetadataVersionEnum = ["VERSION 9.8.1", "VERSION 9.8.2", "VERSION 9.8.2.2", "VERSION 9.8.3", "VERSION 9.8.4", "VERSION 9.9.3", "VERSION 10.2"]',
      'Metadata_Dates/Metadata_Creation'                               => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Metadata_Last_Revision'                          => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Metadata_Future_Review'                          => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Metadata_Delete'                                 => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Creation'                                   => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Last_Revision'                              => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Future_Review'                              => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Metadata_Dates/Data_Delete'                                     => 'Controlled by the DIF/UMM Date or DateTime or EnumType. Must provide an ISO date, an ISO date-time, or a value from the DIF/UMM DateEnum = ["Not provided", "unknown", "present", "unbounded", "future"].',
      'Private'                                                        => 'DIF/UMM PrivateEnum = ["True", "False"]'
    }
  end
end
